name: Build Qt project

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          # Windows
          - os: windows-latest
            qt_arch: win64_msvc2022_64

          # Linux
          - os: ubuntu-latest
            qt_arch: linux_gcc_64

    steps:
      # Récupérer le projet
      - name: Checkout
        uses: actions/checkout@v4

      # Installer Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.3"
          host: ${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }}
          target: desktop
          arch: ${{ matrix.qt_arch }}
          modules: "qt5compat"

      # Configurer CMake
      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release

      # Compiler
      - name: Build
        run: |
          cmake --build build --config Release
